config/routes.rb
Ticketee::Application.routes.draw do

  root :to => 'projects#index'
  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name

  #validations
  validates :name, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		#title of the page
		@title = "Home"
	end

	def new
		#title of the page
		@title = "New Project"

		#create a new project
		@project = Project.new
	end

	def create
		#title of page
		@title = "Create Project"

		#save a new project
		@project = Project.new(params[:project])
		
		if @project.save
			#show the user a success message
			flash[:notice] = "Project has been created"
			redirect_to @project
		else
			#show the user a success message
		flash[:alert] = "Error Creating Project"
		render :action => "new"
		end

		
		
	end

	def show
		

		@project = Project.find(params[:id])

		#title of page
		if @project 
			@title = "Project " +  @project.name
		end
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticketee | <%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
	<div class='flash' id='<%= key %>'>
		<%= value%>
	</div>

<% end %>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f|%>
	<p>
		<%= f.label :name, "Project Name" %>
		<%= f.text_field :name %>
	</p>

	<%= f.submit %>
<% end %>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h2>New Project</h2><br />
<%= render "form" %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>